### ISSUE TITLE
Manutencao nos estilos e adicionar novas funcionalidades a landing page

### ISSUE THREAD

**Issue by MichaelMoranis** [jezyelpassos/Landing-Page-Direito-Trabalhista#1]
Fala Jesiel cara estou propondo fazer manutencao da sua landing page, adicionar novas funcionalidades e melhorar o projeto, isso vai servir como contribuicao em codigo aberto e vai melhorar nossa experiencia como desenvolvedores, logo mais faco uma pull request pra que tu veja as melhorias no projeto ! valeu

**Comment by jezyelpassos** [comment]
Fala mano, acho uma ótima ideia, bom que vou praticando cada vez mais. Qualquer coisa pode mandar mensagem, ou até me ligar. Vamos deixar bem profissional essa landing page. TMJ !

**Comment by MichaelMoranis** [comment]
Mano quando puder manda mensagem, eu perdi seu número !

**Comment by jezyelpassos** [comment]
Mandei lá

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado:terça-feira, 24 de outubro de 2023 08:29
Para: ***@***.***>
Cc:Jezyel ***@***.***>; ***@***.***>
Assunto: Re: [jezyelpassos/Landing-Page-Direito-Trabalhista] Manutencao nos estilos e adicionar novas funcionalidades a landing page (Issue #1)


Mano quando puder manda mensagem, eu perdi seu número !
